import 'dart:convert';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_timezone/flutter_timezone.dart';
import 'package:timezone/data/latest_all.dart' as tz;
import 'package:timezone/timezone.dart' as tz;
import '../models/study_task.dart';

class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  final FlutterLocalNotificationsPlugin _plugin =
      FlutterLocalNotificationsPlugin();

  static const String _tasksPayloadKey = 'study_task';

  // ── Notification channel details ─────────────────────────────────────────

  static const AndroidNotificationDetails _channelDetails =
      AndroidNotificationDetails(
    'study_plan_channel',
    'Study Plan Reminders',
    channelDescription: 'Reminders for your scheduled study tasks.',
    importance: Importance.max,
    priority: Priority.high,
    playSound: true,
    enableVibration: true,
    icon: '@mipmap/ic_launcher',
  );

  static const NotificationDetails _notifDetails = NotificationDetails(
    android: _channelDetails,
    iOS: DarwinNotificationDetails(categoryIdentifier: 'study_task'),
  );

  // ── Initialization ────────────────────────────────────────────────────────

  Future<void> init() async {
    tz.initializeTimeZones();
    final String currentTimeZone = await FlutterTimezone.getLocalTimezone();
    tz.setLocalLocation(tz.getLocation(currentTimeZone));

    const AndroidInitializationSettings androidSettings =
        AndroidInitializationSettings('@mipmap/ic_launcher');

    const DarwinInitializationSettings iosSettings =
        DarwinInitializationSettings(
      requestAlertPermission: true,
      requestBadgePermission: true,
      requestSoundPermission: true,
    );

    const InitializationSettings initSettings = InitializationSettings(
      android: androidSettings,
      iOS: iosSettings,
    );

    await _plugin.initialize(initSettings);

    // Request Android 13+ notification permissions
    await _plugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.requestNotificationsPermission();
  }

  // ── Real-time / Immediate Notifications ──────────────────────────────────

  /// Push an instant notification right now. No scheduling.
  Future<void> showNow({
    required int id,
    required String title,
    required String body,
    String? payload,
  }) async {
    await _plugin.show(
      id,
      title,
      body,
      NotificationDetails(
        android: AndroidNotificationDetails(
          'study_plan_channel',
          'Study Plan Reminders',
          channelDescription: 'Reminders for your scheduled study tasks.',
          importance: Importance.max,
          priority: Priority.high,
          playSound: true,
          enableVibration: true,
          icon: '@mipmap/ic_launcher',
          styleInformation: BigTextStyleInformation(body),
        ),
        iOS: const DarwinNotificationDetails(categoryIdentifier: 'study_task'),
      ),
      payload: payload,
    );
  }

  /// Push an immediate notification when a task is added.
  Future<void> notifyTaskAdded(StudyTask task) async {
    await showNow(
      id: 'added_${task.id}'.hashCode,
      title: '✅ Study Task Added',
      body: '"${task.title}" is scheduled for '
          '${_formatTime(task.scheduledTime)}.',
      payload: jsonEncode({'type': _tasksPayloadKey, 'id': task.id}),
    );
  }

  /// Push an immediate notification when a study plan is generated by AI.
  Future<void> notifyPlanGenerated(int count, String topic) async {
    await showNow(
      id: 'plan_generated'.hashCode,
      title: '🎓 Study Plan Ready!',
      body: 'AI generated $count study sessions for "$topic". '
          'Open the app to review your plan.',
    );
  }

  /// Push an immediate notification when a task is marked complete.
  Future<void> notifyTaskCompleted(StudyTask task) async {
    await showNow(
      id: 'complete_${task.id}'.hashCode,
      title: '🌟 Great Work!',
      body: 'You completed "${task.title}". Keep it up!',
    );
  }

  /// Push reminders for all overdue incomplete tasks on app launch.
  Future<void> notifyOverdueTasks(List<StudyTask> tasks) async {
    final overdue = tasks.where((t) =>
        !t.isCompleted && t.scheduledTime.isBefore(DateTime.now())).toList();

    if (overdue.isEmpty) return;

    if (overdue.length == 1) {
      await showNow(
        id: 'overdue_summary'.hashCode,
        title: '⏰ Overdue Study Task',
        body: '"${overdue.first.title}" was scheduled for '
            '${_formatTime(overdue.first.scheduledTime)}. '
            'Please complete it!',
      );
    } else {
      await showNow(
        id: 'overdue_summary'.hashCode,
        title: '⏰ ${overdue.length} Overdue Study Tasks',
        body: 'You have ${overdue.length} incomplete study sessions. '
            'Open SmartMed to catch up!',
      );
    }
  }

  // ── Scheduled Notifications ───────────────────────────────────────────────

  Future<void> scheduleStudyReminder(StudyTask task) async {
    final scheduledDate = tz.TZDateTime.from(task.scheduledTime, tz.local);

    // Only schedule if it's in the future
    if (scheduledDate.isBefore(tz.TZDateTime.now(tz.local))) return;

    await _plugin.zonedSchedule(
      task.id.hashCode,
      '📚 Study Reminder: ${task.title}',
      task.description.isNotEmpty
          ? task.description
          : 'Time to study! Tap to mark complete.',
      scheduledDate,
      NotificationDetails(
        android: AndroidNotificationDetails(
          'study_plan_channel',
          'Study Plan Reminders',
          channelDescription: 'Reminders for your scheduled study tasks.',
          importance: Importance.max,
          priority: Priority.high,
          playSound: true,
          enableVibration: true,
          icon: '@mipmap/ic_launcher',
          styleInformation: BigTextStyleInformation(task.description),
          actions: [
            AndroidNotificationAction(
              'mark_complete_${task.id}',
              '✅ Mark Complete',
              cancelNotification: true,
            ),
          ],
        ),
        iOS: DarwinNotificationDetails(
          categoryIdentifier: 'study_task',
          subtitle: task.description,
        ),
      ),
      payload: jsonEncode({'type': _tasksPayloadKey, 'id': task.id}),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
    );
  }

  Future<void> scheduleIncompleteReminder(StudyTask task) async {
    final followUp = tz.TZDateTime.from(
      task.scheduledTime.add(const Duration(hours: 1)),
      tz.local,
    );
    if (followUp.isBefore(tz.TZDateTime.now(tz.local))) return;

    await _plugin.zonedSchedule(
      '${task.id}_followup'.hashCode,
      '⏰ Incomplete Task: ${task.title}',
      "You haven't completed this study session yet. Mark it complete when done!",
      followUp,
      _notifDetails,
      payload: jsonEncode({'type': _tasksPayloadKey, 'id': task.id}),
      androidScheduleMode: AndroidScheduleMode.exactAllowWhileIdle,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
    );
  }

  // ── Cancellation ──────────────────────────────────────────────────────────

  Future<void> cancelTaskNotifications(String taskId) async {
    await _plugin.cancel(taskId.hashCode);
    await _plugin.cancel('${taskId}_followup'.hashCode);
    await _plugin.cancel('added_$taskId'.hashCode);
    await _plugin.cancel('complete_$taskId'.hashCode);
  }

  Future<void> cancelAll() async {
    await _plugin.cancelAll();
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  String _formatTime(DateTime dt) {
    final hour = dt.hour.toString().padLeft(2, '0');
    final min = dt.minute.toString().padLeft(2, '0');
    final day = dt.day.toString().padLeft(2, '0');
    final month = dt.month.toString().padLeft(2, '0');
    return '$hour:$min on $day/$month';
  }
}
